version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - software-startup-db:/var/lib/mysql

  backend:
    image: software-startup/backend
    build:
      context: capi
    restart: always
    ports:
      - '8082:8082'
      # mount the local directory to the container, so that we can edit the code
      # and see the changes in the container
    volumes:
      - ./capi:/app

  rad:
    image: software-startup/rad
    build:
      context: ./rad
    restart: always
    ports:
      - '8080:8080'
      # mount the local directory to the container, so that we can edit the code
      # and see the changes in the container
    volumes:
      - ./rad:/app

  dbpedia-spotlight:
    image: dbpedia/dbpedia-spotlight:latest
    command: spotlight.sh en
    ports:
      - "2222:80"
    restart: unless-stopped
    volumes:
      - spotlight-model:/opt/spotlight

  nlp:
    image: software-startup/nlp
    build:
      context: ./nlp
    restart: always
    ports:
      - '8081:8080'
    volumes:
      - ./nlp:/app

volumes:
  software-startup-db:
  spotlight-model:
