version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - software-startup-db:/var/lib/mysql
  rad:
    image: software-startup/rad
    build:
      context: ./rad
    restart: always
    ports:
      - '8080:8080'
      # mount the local directory to the container, so that we can edit the code
      # and see the changes in the container
    volumes:
      - ./rad:/app

volumes:
  software-startup-db:
